### ISSUE TITLE
FAILED to handle event error every ~500ms — trailing spaces no longer highlighted (VS Code Insiders 1.122.0)

### ISSUE THREAD

**Issue by ThisIsDavidHan** [shardulm94/vscode-trailingspaces#81]
Trailing spaces are no longer highlighted in the editor. The Output panel logs the following error approximately every 500ms whenever the document changes:

```
2026-06-01 09:28:55.013 [error] ExtensionError: Error in extension shardulm94.trailing-spaces: FAILED to handle event
    at up.value (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:669:134671)
    at E._deliver (...extensionHostProcess.js:431:3244)
    at E._deliverQueue (...extensionHostProcess.js:431:3333)
    at E.fire (...extensionHostProcess.js:431:3667)
    at xw.$acceptModelChanged (...extensionHostProcess.js:558:113280)
    at i._doInvokeHandler (...)
    ...
```

The error originates from `$acceptModelChanged`, meaning it fires on every document edit keystroke or change event — making the editor log-spam and the extension entirely non-functional.

**Steps to Reproduce**

1. Install VS Code Insiders 1.122.0-insider on macOS.
2. Install Trailing Spaces v0.4.1.
3. Open any file with trailing spaces.
4. Observe: no highlighting appears.
5. Open Output panel → select "Log (Extension Host)": error fires on every edit.

**Expected Behavior**

Trailing spaces are highlighted in red (or per configured color) as they were in previous versions.

**Actual Behavior**

No highlighting. Continuous `FAILED to handle event` errors from the `$acceptModelChanged` handler, one per document change event (~500ms cadence during typing).

**Environment**

| | |
|---|---|
| OS | macOS |
| VS Code | 1.122.0-insider |
| Extension version | 0.4.1 |

**Hypothesis**

VS Code 1.122.0-insider likely changed the shape or semantics of the `TextDocumentChangeEvent` or a related model-change API that the extension consumes in its `$acceptModelChanged` listener. The unhandled exception is swallowed by the extension host but prevents the decoration from being applied. Checking what changed in VS Code's extension API between the last working version and 1.122.0-insider (particularly around `workspace.onDidChangeTextDocument` or `TextDocument` model events) would narrow this down quickly.

**Comment by ThisIsDavidHan** [comment]
**Confirmed on Windows as well.**

Same behaviour on Windows with VS Code Insiders 1.122.0-insider:

| | |
|---|---|
| OS | Windows 11 |
| VS Code | 1.122.0-insider |
| Extension version | 0.4.1 |

Identical error cadence — `FAILED to handle event` logged in the Extension Host output every ~500ms on any document change, no trailing-space decorations applied. The issue is not macOS-specific; the `$acceptModelChanged` API breakage affects all platforms on this Insiders build.

**Comment by sergiitk** [comment]
Confirming with shardulm94.trailing-spaces `0.4.1` and VS Code 1.123.0:

Version: 1.123.0
Commit: 6a44c352bd24569c417e530095901b649960f9f8
Date: 2026-06-03T11:29:03+02:00 (16 hrs ago)
Electron: 42.2.0
ElectronBuildId: 14159160
Chromium: 148.0.7778.97
Node.js: 24.15.0
V8: 14.8.178.14-electron.0
OS: Darwin arm64 25.5.0

**Comment by sergiitk** [comment]
And "Trim on Save" feature is broken too.

**Comment by ChrisZ-IT** [comment]
Same issue in Linux. I also have this issue on my windows 11 work laptop. So I decided to test on my personal PC

 I use devbox on my personal PC. So I can bounce between versions of vscode since I made a copy of my 1.122.1 devbox before upgrading it to 1.123.0. Extension  works on 1.122.1 but breaks in 1.123.0.

Working version:
Version: 1.122.1
Commit: 8761a5560cfd65fdd19ce7e2bd18dab5c0a4d84e
Date: 2026-05-29T09:25:37+02:00
Electron: 39.8.8
ElectronBuildId: 13870025
Chromium: 142.0.7444.265
Node.js: 22.22.1
V8: 14.2.231.22-electron.0
OS: Linux x64 6.19.14-ogc5.1.fc44.x86_64

Broken version:
Version: 1.123.0
Commit: 6a44c352bd24569c417e530095901b649960f9f8
Date: 2026-06-03T11:29:03+02:00
Electron: 42.2.0
ElectronBuildId: 14159160
Chromium: 148.0.7778.97
Node.js: 24.15.0
V8: 14.8.178.14-electron.0
OS: Linux x64 6.19.14-ogc5.1.fc44.x86_64

When I `ctrl+shift+P` and try and delete some trailing spaces i get this error:
`Command 'Trailing Spaces: Delete' resulted in an error (0,util_1.isNullOrUndefined) is not a function`

Looks like [this](https://github.com/shardulm94/vscode-trailingspaces/pull/78) pull request from September says it fixes this util_1 function error. Not a js dev so id have to rely on Ai to confirm it though 🤷

**Comment by Bibz87** [comment]
Last commit was 4 years ago... Should we consider the repository and the extension as dead? 🫤

**Comment by philsherry** [comment]
All similar extensions seem to have the same maintenance lapses, some last updated as far back as 10 years ago. 

Anyone found a good alternative that stays maintained?

**Comment by shardulm94** [comment]
Can you test this with the latest release v0.4.2? I merged https://github.com/shardulm94/vscode-trailingspaces/pull/78 and hopefully that fixes it.

**Comment by jamesderlin** [comment]
Trailing whitespace is highlighted again for me after installing 0.4.2 and restarting VS Code.

**Comment by dmotte** [comment]
@shardulm94 it works perfectly now! Thank you so much! 😄 

FTR I tested it on Debian 13 (trixie)

Version: 1.125.1
Commit: fcf604774b9f2674b473065736ee75077e256353
Date: 2026-06-19T08:39:34Z
Electron: 42.2.0
ElectronBuildId: 14159160
Chromium: 148.0.7778.97
Node.js: 24.15.0
V8: 14.8.178.14-electron.0
OS: Linux x64 6.12.90+deb13.1-amd64
